# Generated by Django 5.0.2 on 2026-04-23 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.avatars.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference", "0003_faction_on_primary_and_align_colors"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("basic_frame", "Basic frame"),
                            ("realistic", "Realistic"),
                            ("dark", "Dark"),
                            ("heraldic", "Heraldic"),
                        ],
                        default="basic_frame",
                        max_length=32,
                    ),
                ),
                (
                    "source_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.avatars.models.avatar_source_upload_to,
                    ),
                ),
                (
                    "generated_image",
                    models.ImageField(
                        upload_to=apps.avatars.models.avatar_generated_upload_to
                    ),
                ),
                ("is_current", models.BooleanField(default=False)),
                (
                    "faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avatars",
                        to="reference.faction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avatars",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="avatarasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("user",),
                name="avatars_single_current_per_user",
            ),
        ),
    ]
