# Generated by Django 5.0.2 on 2026-04-29 08:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_house_decks_two_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faction',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть HEX-значением вида #AABBCC.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AlterField(
            model_name='faction',
            name='on_primary',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Цвет должен быть HEX-значением вида #AABBCC.', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
