# Generated by Django 5.0.2 on 2026-04-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_f2ad08_idx',
            old_name='notif_user_unread_idx',
        ),
    ]
