# Generated by Django 5.0.2 on 2026-04-22 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("CROWN", "Crown"), ("SHIT", "Shit")], max_length=8
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_match_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="games.gamesession",
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_match_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="ratings_mat_session_7008d6_idx",
                    ),
                    models.Index(
                        fields=["to_user", "vote_type"],
                        name="ratings_mat_to_user_72a817_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="matchvote",
            constraint=models.UniqueConstraint(
                fields=("session", "from_user", "to_user"),
                name="ratings_vote_unique_pair_per_session",
            ),
        ),
        migrations.AddConstraint(
            model_name="matchvote",
            constraint=models.CheckConstraint(
                check=models.Q(("from_user", models.F("to_user")), _negated=True),
                name="ratings_vote_from_user_not_equal_to_user",
            ),
        ),
    ]
