# Generated by Django 5.0.2 on 2026-04-22 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0006_house_decks_two_variants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('planning_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sessions', to=settings.AUTH_USER_MODEL)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='reference.housedeck')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='reference.gamemode')),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('castles', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_winner', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='reference.faction')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='games.gamesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='outcome', serialize=False, to='games.gamesession')),
                ('rounds_played', models.PositiveSmallIntegerField()),
                ('end_reason', models.CharField(choices=[('castles_7', 'Seven Castles'), ('timer', 'Timer'), ('rounds_end', 'Rounds End'), ('early', 'Early'), ('other', 'Other')], max_length=20)),
                ('final_note', models.TextField(blank=True)),
                ('mvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mvp_outcomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['status', 'scheduled_at'], name='games_games_status_7e2b84_idx'),
        ),
        migrations.AddIndex(
            model_name='gamesession',
            index=models.Index(fields=['created_by', 'status'], name='games_games_created_059744_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['session', 'user'], name='games_parti_session_bd6fd1_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['user', 'is_winner'], name='games_parti_user_id_499365_idx'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='games_participation_user_once'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('session', 'faction'), name='games_participation_faction_once'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(condition=models.Q(('place__isnull', False)), fields=('session', 'place'), name='games_participation_unique_place_in_session'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_winner', True)), fields=('session',), name='games_participation_single_winner'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.CheckConstraint(check=models.Q(('is_winner', False), ('place', 1), _connector='OR'), name='games_participation_winner_requires_first_place'),
        ),
        migrations.AddConstraint(
            model_name='outcome',
            constraint=models.CheckConstraint(check=models.Q(('rounds_played__gte', 1)), name='games_outcome_rounds_played_gte_1'),
        ),
    ]
