# Generated by Django 5.0.2 on 2026-04-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_match_timeline_event'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='matchtimelineevent',
            new_name='games_match_session_b17af8_idx',
            old_name='games_timeline_session_happened_idx',
        ),
        migrations.RenameIndex(
            model_name='sessioninvite',
            new_name='games_sessi_session_cd1676_idx',
            old_name='games_sessioninvite_rsvp_idx',
        ),
        migrations.AlterField(
            model_name='matchtimelineevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roundsnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sessioninvite',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
