# Generated by Django 5.0.2 on 2026-04-23 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_enforce_unique_email"),
        ("avatars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="current_avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_for_profiles",
                to="avatars.avatarasset",
            ),
        ),
    ]
